### ISSUE TITLE
Esbuild: could not resolve "canihazusername" 

### ISSUE THREAD

**Issue by AliNisarAhmed** [cupcakearmy/canihazusername#12]
## Environment 

- OS: Pop OS
- Package version: `2.3.3`
- Node version: `v17.9.1`
- build system: [`esbuild`](https://hexdocs.pm/phoenix/asset_management.html) (using [phoenix framework](https://www.phoenixframework.org/))

## Error

`Could not resolve 'canihazusername'`

`The module "./dist/index.mjs" was not found on the file system`

![image](https://user-images.githubusercontent.com/35175560/172099463-71b42aca-02f8-4526-8907-88b7884570c9.png)
![image](https://user-images.githubusercontent.com/35175560/172099582-1084d902-1301-4fe6-b52f-3ac2f4da7c72.png)

Not sure if this is related to the latest version, or if the error is related to this library, but posting here to get any help.

**Comment by cupcakearmy** [comment]
Can you try version `2.3.4`?
Sry, I messed up the package config.

**Comment by AliNisarAhmed** [comment]
`2.3.4` fixes this!, thanks
