### ISSUE TITLE
Library code is not included in npm pacakge in v2.2.0

### ISSUE THREAD

**Issue by cakecatz** [cupcakearmy/canihazusername#9]
In `2.1.1`, it was included.

https://www.jsdelivr.com/package/npm/canihazusername

![image](https://user-images.githubusercontent.com/6136383/142762573-2246c40c-64da-4423-9fa6-7e1ac96d92c9.png)

![image](https://user-images.githubusercontent.com/6136383/142762589-54df6e34-8a5e-4c2d-b30d-4e74259046ff.png)

**Comment by cupcakearmy** [comment]
ups, i'll see what i've messed up, thanks for reporting!

**Comment by cupcakearmy** [comment]
should be fixed

**Comment by cakecatz** [comment]
@cupcakearmy Thank you!
